language: python
sudo: false

cache:
  directories:
    - $HOME/.pip-cache/

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.2"
      env: TOXENV=py32 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.3"
      env: TOXENV=py33 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.4"
      env: TOXENV=py34 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.5"
      env: TOXENV=py35 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "pypy"
      env: TOXENV=pypy PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "pypy3"
      env: TOXENV=pypy3 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "2.7"
      env: TOXENV=docs PIP_DOWNLOAD_CACHE=$HOME/.pip-cache

install:
- virtualenv --version
- git config --global user.email "travisci@jasonantman.com"
- git config --global user.name "travisci"
- pip install tox
- pip install codecov
- pip freeze
- virtualenv --version
script:
  - tox -r

after_success:
  - codecov

notifications:
  email:
    on_success: always
    on_failure: always
  pushover:
    users:
    - secure: Your_encrypted_Pushover_User_Key_Here_(repository_specific)
    api_key:
      secure: Your_encrypted_Pushover_api/application_key_here_(repository_specific)
branches:
  except:
    - "/^noci-.*$/"
