language: python
sudo: false

cache:
  directories:
    - $HOME/.pip-cache/

env:
  - TOXENV=py26 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  - TOXENV=py27 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  - TOXENV=py32 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  - TOXENV=py33 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  - TOXENV=py34 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  - TOXENV=docs PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  - TOXENV=pypy PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  - TOXENV=pypy3 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  - TOXENV=cov PIP_DOWNLOAD_CACHE=$HOME/.pip-cache

install:
  - git config --global user.email "travisci@jasonantman.com"
  - git config --global user.name "travisci"
  - pip install tox
  - pip install codecov
  - pip freeze

script:
  - tox -r

after_success:
  - codecov

notifications:
  email:
    on_success: always
    on_failure: always

branches:
  except:
    - /^noci-.*$/
